### ISSUE TITLE
Fee Config Manager precompile does not work

### ISSUE THREAD

**Issue by mculinovic** [ava-labs/avalanche-cli#176]
**Avalanche-cli version: 0.2.1**

**Reproduction steps:**
* Run `avalanche subnet create {subnet_name} --evm` 
* Enable fee config manager precompile
* Run `avalanche subnet deploy {subnet_name}` and deploy locally

I'm using `brownie` as development framework so I'm connecting to the interface as follows:
* I've copied over `IFeeManager.sol` from https://github.com/ava-labs/subnet-evm/blob/master/contract-examples/contracts/IFeeManager.sol
* Instantiate the interface in brownie:
```
fm_address = '0x0200000000000000000000000000000000000003'
fee_manager = interface.IFeeManager(fm_address)
```
* Interact with fee manager:
```
fee_config = fm_interface.getFeeConfig()
print(fee_config)
```
* Instantiating the interface results in error:
```
ContractNotFound: No contract deployed at 0x0200000000000000000000000000000000000003
```

**Other investigation related to the issue**
* Export the genesis by running `avalanche subnet describe {subnet_name} --genesis`
* Use that genesis in `subnet-evm/scripts/run.sh` to run the subnet locally
* Interacting with local subnet started by `run` script works as expected
* When running subnet locally from avalanche-cli native minter and deployer list precompiles work as expected. Using the following snippet to instantiate them (same as for fee config manager):
```
nm_address = '0x0200000000000000000000000000000000000001'
native_minter = interface.INativeMinter(nm_address)
deployer_list_address = '0x0200000000000000000000000000000000000000'
deployer_list = interface.IAllowList(deployer_list_address)
```

**Comment by holisticode** [comment]
This is due to a lack of a proper update process for `avalanche-cli`. The subnet-evm fee config management precompile is only available from subnet-evm 0.2.5 onwards. `avalanche-cli` in version 0.2.0 supported only lower versions. An upgrade to `avalanche-cli` 0.2.1 was required, which the ticket owner correctly did.

However, there is no documented clean update path. Just running the install script again will only update `avalanche-cli` itself, but not the required binaries like `avalanche-go` and `subnet-evm`.

As a workaround, the `~/.avalanche-cli/bin` directory can be deleted. Afterwards the subnet needs to be re-deployed to the local network, which will download the latest supported versions.

The version 0.2.2 will contain a cleaner update path.
