### ISSUE TITLE
[Tutorial] Deploy smart contracts on your subnet

### ISSUE THREAD

**Issue by dasconnor** [ava-labs/avalanche-cli#452]

**Comment by Codie-Petersen** [comment]
@dasconnor My company Asteres Technologies and CodeLink ended up making a tutorial for deploying a contract to a local subnet. It's still fresh in my head, would you like me to take care of this. 

This is the section for the subnet stuff: https://github.com/CodeLinkIO/MoveAndWhap#local-subnet-deploy

If you want I can make something similar with like a hello world contract but be more specific about the contract deployment steps rather than relying on the script have made for it.
