### ISSUE TITLE
avalanche-cli based VM e2e testing suite

### ISSUE THREAD

**Issue by aaronbuchwald** [ava-labs/avalanche-cli#559]
Avalanche VMs want the ability to perform e2e tests in a variety of settings sometimes with a high degree of fine grained control, so that they perform tests in changing environment and test different scenarios.

Currently we have a large amount of duplicated and sometimes inconsistent code dedicated to e2e testing across our VM repos, which we could ideally formalize to follow a single format, so this ticket is intended to start a discussion about what we need from the avalanche-cli or another off-shoot repo if needed to support a portable e2e testing suite across VM repos that reduces that duplicated code.

We want the following abilities for every VM:

- Launch a simple 5 node network with a pre-specified blockchain to launch on a subnet - specify the VM and the genesis bytes (via script and e2e test ginkgo BeforeSuite and AfterSuite)
- Launch a single node with staking disabled so that tests can be easily performed without whitelisting subnets (via script and e2e test ginkgo BeforeSuite and AfterSuite)
- Start a new node with the same set of subnets whitelisted or staking disabled so that we can confirm whatever was created by the test can be synced correctly
- Use a global node, chain, and subnet configs to set a default config for every node in the network
- Use a node specific node, chain, and subnet config to configure a specific node in the network

**Comment by aaronbuchwald** [comment]
Ik these are roughly supported now, in an ideal world we would have a repo that treats testing as a priority, such that each of these use cases could be a single function call or at least as simple as possible, whereas now it requires setting up a logger, server, and then making multiple client calls in order to configure a network.

**Comment by aaronbuchwald** [comment]
Another highly desirable feature would be to remove the need to shut down the whole network and restart it with whitelisted subnets by pre-calculating what the subnetID based off of the transaction that will be used to create the subnet.

**Comment by holisticode** [comment]
* `Launch a simple 5 node network with a pre-specified blockchain to launch on a subnet - specify the VM and the genesis bytes (via script and e2e test ginkgo BeforeSuite and AfterSuite)`. 
We do this already for our own tests

* `Launch a single node with staking disabled so that tests can be easily performed without whitelisting subnets (via script and e2e test ginkgo BeforeSuite and AfterSuite)`
This is not yet supported as such. We could start a network of size 1 but this is untested.

* `Start a new node with the same set of subnets whitelisted or staking disabled so that we can confirm whatever was created by the test can be synced correctly`
This is a feature available in ANR.  We could provide a convenience call for e2e tests.

* `Use a global node, chain, and subnet configs to set a default config for every node in the network`
CLI supports this via a flag. Check https://github.com/ava-labs/avalanche-cli#modifying-your-subnet-deployment. Applies avalanchego flags to all nodes. Chain and subnet configs are applicable to all nodes by default in CLI.

* Use a node specific node, chain, and subnet config to configure a specific node in the network
This is currently only possible in ANR, not via CLI. We could add convenience calls for e2e tests.

In general, CLI could add "frontend" APIs for such requests to simplify the ANR implementation behind it.

**Comment by aaronbuchwald** [comment]
"frontend" APIs for e2e tests to simplify the `BeforeSuite` and `AfterSuite` functions is exactly what I'm looking for. I understand most of the functionality is supported, but don't want to have a large amount of setup code duplicated across every VM repo.

**Comment by felipemadero** [comment]
> Another highly desirable feature would be to remove the need to shut down the whole network and restart it with whitelisted subnets by pre-calculating what the subnetID based off of the transaction that will be used to create the subnet.

currently CLI use snapshots with already whitelisted and available subnet IDs

**Comment by felipemadero** [comment]
avoiding that code duplication and unifying and making all clean and well designed is a very good idea. I can also insist that ANR snapshots are a good way to quickly set a starting state for tests. probably we can make a snapshot for 1 node and also provide the current one for 5 nodes. CLI has mechanism to load a arbitray snapshot but probably some test/debug may be needed for 1 node case.
