### ISSUE TITLE
 Can ganache-cli be used as a blockchain to access the subnet

### ISSUE THREAD

**Issue by BigOceanGG** [ava-labs/avalanche-cli#593]
Is it enough to give the chainID of the created subnet a unique ID that does not exist online? Can ganache-cli be used as a blockchain to access the subnet？

**Comment by dasconnor** [comment]
You should pick a chainID that is not taken on https://chainlist.org/. Then, when you go to production, you should register yours.

As far as Ganache, you shouldn't need to use it because the subnet already generates a blockchain for you to use. AFAIK, Truffle would be the one you'd want to use to interact with the deployed chain, not ganache.

**Comment by BigOceanGG** [comment]
@dasconnor That is to say, after I create the subnet, the blockchain is automatically provided, and I don’t need to connect to another existing chain, right?

**Comment by dasconnor** [comment]
yep!

**Comment by BigOceanGG** [comment]
@dasconnor How to put the nodes of the subnet on different servers, so that the downtime of one server will not affect the subnet

**Comment by dasconnor** [comment]
That's a better answered by our support team on Discord, I'd suggest you ask there: https://chat.avax.network/

**Comment by BigOceanGG** [comment]
@dasconnor I can't find the place to post in discord, and I don't have permission to send messages in the channel. I only see the channel "start here", and I have verified it
<img width="566" alt="image" src="https://user-images.githubusercontent.com/42688345/218243329-b156ae26-f46e-4383-a3b7-308ba692ebb0.png">
