### ISSUE TITLE
set up a notification here into this chat of any new release of the dependencies we use

### ISSUE THREAD

**Issue by felipemadero** [ava-labs/avalanche-cli#644]
avago, subnet-evm, spacesvm, custom-vms, in future possibly hypervms etc.
posibility: https://cyublog.com/articles/dev-en/github-slack/

**Comment by holisticode** [comment]
Rather than just a notification, we should have all those VM trigger a new `avalanche-cli` build on each new release right away. Otherwise we just get notified of a new release, but still don't know if the new release passes CI and we're only going to find out (painfully) on an unrelated PR of ours, later.
